### ISSUE TITLE
Remove specification of machine names in KayVee/libraft cluster configuration

### ISSUE THREAD

**Issue by allengeorge** [allengeorge/libraft#38]
Currently both the KayVee and libraft cluster configuration files require that you specify the _names_ of all machines in the cluster. For example:

```
members:
    - id: SERVER_00
      kayVeeUrl: http://localhost:6080
      raftEndpoint: localhost:9080
    - id: SERVER_01
      kayVeeUrl: http://localhost:6085
      raftEndpoint: localhost:9085
    ...
```

This is unnecessary, especially now that each machine does a handshake in which it provides some identifying information.
